### ISSUE TITLE
How to use tweaks? (add to readme)

### ISSUE THREAD

**Issue by dimasites** [Brugman/cyberpanel-design-tweaks#1]
Hi @Brugman! Thank for sharing tweaks, but where i can find CSS-file which i need to replace? Or maybe in web GUI of cyberpanel i can add any css-tweaks for inject?

I know about use Chrome's [User CSS plugin](https://chrome.google.com/webstore/detail/user-css/okpjlejfhacmgjkmknjhadmkdbcldfcb) but maybe you can suggest better method?

**Comment by Brugman** [comment]
In the newer versions of CP there's a Design link in the menu. On that page you can choose a theme, which populates the textarea below it with CSS. In that same textarea you can add your own CSS.

Keep in mind that selecting a theme will wipe all your custom CSS. So if you want to check out the themes make a backup (copy to notepad) of your custom CSS, so you can put it back later.

![use-css-design-tweaks](https://user-images.githubusercontent.com/2203813/220446682-063d9dea-3b17-4791-b9e0-99591761deba.gif)
